spring:
  application:
    name: notion-quiz-generator
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:7b-instruct

notion:
  api:
    secret: ${NOTION_SECRET}
    version: "2022-06-28"
    base-url: "https://api.notion.com/v1"
